### ISSUE TITLE
Run a standalone code with library dependencies that calls a remote spreadsheet? (need an example...)

### ISSUE THREAD

**Issue by maximelebreton** [googlesamples/apps-script#18]
Hello, thank you for the great work, and sorry for my basic question.

**Here is my scenario:**
- I have a standalone `MyLibrary.gs` saved as a library, and configured with `node-google-apps-script` 
- which itself depends from other libraries ([cheerio-gasify](https://github.com/3846masa/cheerio-gasify) for example)  
- and i want to test my code from the `node cli`
- on a remote spreadsheet that calls my library

Is it possible ?
and how can i make it work?

A working example would be great.

Thanks!

**Comment by grant** [comment]
I suppose that is possible. Closing as there's no issue with the current samples reported here.
