### ISSUE TITLE
Ruby sample should show error

### ISSUE THREAD

**Issue by rootux** [googlesamples/apps-script#20]
in the sample ruby program here:
https://developers.google.com/apps-script/guides/rest/quickstart/ruby

Missing the following to print the actual error:
```
rescue Google::Apis::ClientError => e
  # The API encountered a problem before the script started executing.
  puts "Error calling API!"
  puts sprintf('Caught error %s', e) 
```

**Comment by grant** [comment]
Thanks for the suggestion, however, the source code for that sample is not in this repo.
