### ISSUE TITLE
Docs translate sample is broken

### ISSUE THREAD

**Issue by MrCsabaToth** [googlesamples/apps-script#29]
`<script src="//polymerstaticfilesfortesting.appspot.com/bower_components/webcomponentsjs/webcomponents.min.js"></script>` in `sidebar.html` is 404, the other elements under the same URL seems to be there though.

I tried to substitute https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.1.0/webcomponents-loader.js but the whole thing errors out left and right.

**Comment by MrCsabaToth** [comment]
Looks like this will be pre 2.0 polymer elements, I'm crafting a repo so I can serve files for the demo https://github.com/gdgfresno/DocsAddonDemoHelper

**Comment by MrCsabaToth** [comment]
Aaaand https://gdgfresno.github.io/DocsAddonDemoHelper/bower_components/webcomponentsjs/webcomponents.min.js is served, let's see if the demo works now...

**Comment by grant** [comment]
Thanks @MrCsabaToth. The Doc add-on issue is a known issue and will be updated soon.

**Comment by MrCsabaToth** [comment]
Now something is looking for `bower_components/paper-input/paper-input-decorator.html` which is a v0.5 (!!!) polymer element. What a headache! I looked at the Slide translate demo, it does not use polymer, but I'd be happy to demo and feature polymer along with AppScript for my GDG

**Comment by MrCsabaToth** [comment]
I feel like I'm almost there, just a couple of more hoops...

**Comment by grant** [comment]
If you can wait until tomorrow, I will update the version.

**Comment by MrCsabaToth** [comment]
Turns out that the `bower_components/paper-input/paper-input-decorator.html` is not essential. Once I revert to my repo to serve the elements, I just need to do a little conversion of the sidebar.html. Basically moving the `label=` values into the DOM text for `paper-radio-button`s and `paper-checkbox`:

```
    <div class="col">
      <h3>Selected text</h3>
      <paper-radio-group id="origin" selected="auto">
        <paper-radio-button name="auto" id="radio-origin-auto">Auto-detect</paper-radio-button>
        <paper-radio-button name="en" id="radio-origin-en">English</paper-radio-button>
        <paper-radio-button name="fr" id="radio-origin-fr">French</paper-radio-button>
        <paper-radio-button name="de" id="radio-origin-de">German</paper-radio-button>
        <paper-radio-button name="ja" id="radio-origin-ja">Japanese</paper-radio-button>
        <paper-radio-button name="es" id="radio-origin-es">Spanish</paper-radio-button>
      </paper-radio-group>
    </div>
    <div class="col">
      <h3>Translate into</h3>
      <paper-radio-group id="dest" selected="ja">
        <paper-radio-button name="en" id="radio-dest-en">English</paper-radio-button>
        <paper-radio-button name="fr" id="radio-dest-fr">French</paper-radio-button>
        <paper-radio-button name="de" id="radio-dest-de">German</paper-radio-button>
        <paper-radio-button name="ja" id="radio-dest-ja">Japanese</paper-radio-button>
        <paper-radio-button name="es" id="radio-dest-es">Spanish</paper-radio-button>
      </paper-radio-group>
    </div>
```

`  <paper-checkbox id="save-prefs">Use these languages by default</paper-checkbox>
`

**Comment by MrCsabaToth** [comment]
Maybe Polymer 2.0 is not too big whop either, but I move on now

**Comment by MrCsabaToth** [comment]
Using my repo before the issue is fixed:
```
<script src="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/webcomponentsjs/webcomponents.min.js"></script>
<link rel="import" href="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/polymer/polymer.html">
<link rel="import" href="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/font-roboto/roboto.html">
<link rel="import" href="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/paper-input/paper-input.html">
<link rel="import" href="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/paper-button/paper-button.html">
<link rel="import" href="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/paper-checkbox/paper-checkbox.html">
<link rel="import" href="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/paper-radio-group/paper-radio-group.html">
<link rel="import" href="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/paper-radio-button/paper-radio-button.html">
<link rel="import" href="//gdgfresno.github.io/DocsAddonDemoHelper/bower_components/paper-input/paper-input-decorator.html">
```

I have to admit that the code tells!
`<!-- Replace these import links with links to files hosted on your own server -->`

**Comment by grant** [comment]
@MrCsabaToth I've updated the sample. Thanks for the report.

**Comment by MrCsabaToth** [comment]
It works! Polymer is advised or not for AddOn UI?

**Comment by grant** [comment]
I would refrain from adding Polymer or other libraries to Apps Script unless really necessary.
