### ISSUE TITLE
Error with appscript Cannot find method JSON.parse

### ISSUE THREAD

**Issue by Jakedismo** [googlesamples/apps-script#30]
So I have this small function that fetches JSON from our companys API and pushes it to Google sheets, everything was working ok yesterday but now when I run the script I get the error 
"Cannot find function parse in [object Object] I have no idea where this is coming from since if I try to
write JSON. TAB it shows there is a parse function. Any thoughts? Is this a bug?

`function pullJSON() {
  options = {muteHttpExceptions: true};
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheets = ss.getSheets();
  var sheet = ss.getActiveSheet();

  var url="API PATH"; // Paste your JSON URL here
  
  var response = UrlFetchApp.fetch(url, options); // get feed
  var dataAll = JSON.parse(response.getContentText()); //
  var dataSet = dataAll;
  
  
  var rows = [],
      data;
  

  for (i = 0; i < dataSet.length; i++) {
    data = dataSet[i];
    rows.push([data.title,new Date(data.promotionStartDate),new Date(data.promotionDateEnd)]); //your JSON entities here
  }

  dataRange = sheet.getRange(1, 1, rows.length, 3); // 3 Denotes total number of entites
  dataRange.setValues(rows);
}
`

**Comment by erickoledadevrel** [comment]
FYI, this GitHub issue tracker should be used to report bugs with our samples and is not a forum for general Apps Script questions. See the [Apps Script Support page](https://developers.google.com/apps-script/support) for information on how to get help.

My guess is that you have a variable defined somewhere called "JSON", and so when you call `JSON.parse()` it's looking at that object instead and not finding the method.
